title: 1st FAIR Workshop on Resilient AI
title_homepage: <span class="ws-subtitle">1st FAIR Workshop on</span><span class="ws-title">Resilient AI</span>
title_navbar: <span class="navbar-subtitle">1st FAIR Workshop on</span><span class="navbar-title">Resilient AI</span>
preposition: at
description: >-
  Official website of the 1st FAIR Workshop on Resilient AI. Naples, Italy, February 27, 2024.
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://fair-resilient-ai.github.io" # the base hostname & protocol for your site, e.g. https://example.com
show_program: true
subtitle: February 27, 2024 - Naples, Italy

theme: jekyll-theme-conference

# Build settings
markdown: kramdown
sass:
  style: compressed

# Additional exclude from processing
exclude:
  - vendor
  - .github/
  - README.md
  - LICENSE.md
  - REDISTRIBUTED.md
  - purgecss.config.js

# Collections and their defaults
collections:
  talks:
    output: true
    permalink: /:collection/:title/
  speakers:
    output: true
    permalink: /:collection/:title/
  rooms:
    output: true
    permalink: /:collection/:title/

defaults:
  - scope:
      path: ""
      type: talks
    values:
      layout: talk
  - scope:
      path: ""
      type: speakers
    values:
      layout: speaker
  - scope:
      path: ""
      type: rooms
    values:
      layout: room


conference:

  # Language
  lang: en

  # Show theme errors:
  show_errors: True

  # Navigation bar
  navigation:
    # logo:
    #   name: FAIR Foundation
    #   # img: ''
    #   url: 'https://future-ai-research.it/'
    links:
      - name: Program
        disabled: true
        relative_url: /program/
      - name: Talks
        disabled: true
        relative_url: /talks/
      - name: Speakers
        disabled: true
        relative_url: /speakers/
      - name: Location
        relative_url: /location/
      # - name: Previous Editions
      #   menu:
      #     - name: 2020 (current)
      #       disabled: true
      #     - name: 2019
      #       relative_url: /2019/
      #     - name: 2018
      #       relative_url: /2018/

  # Link Preview for Sharing
  link_preview:
    # also adapt "preposition" property at top for more meaningful descriptions
    disable: false
    img:
      twitter: 'twitter_preview.png'      # inside /assets/images/
      open_graph: 'facebook_preview.png'  # inside /assets/images/

  # Main landing page
  main:
    # logo:
    #   img: ''
    links:
      - name: Program
        disabled: true
        relative_url: /program/
        icon: calendar
      - name: Location
        relative_url: /location/
        icon: map-marker
        disabled: true
      - name: Registration
        disabled: true
        absolute_url: ''

  # Information boxes
  # info_bars:
  #   - title: Welcome to the Conference Theme for Jekyll!
  #     color: primary
  #     main_only: true
  #     text: |
  #       The Theme was originally made for the [Winterkongress](https://www.digitale-gesellschaft.ch/kongress/), a yearly conference of the [Digital Society Switzerland](https://digitale-gesellschaft.ch/).

  #       ---

  #       See the [README](github.com/DigitaleGesellschaft/jekyll-theme-conference/) on the project's GitHub repository for further information on how to configure and adapt it to your needs.
  #   - text: This is just some random content for demonstration purposes.
  #     color: warning
  #     pages_only: true

  # Live indications
  live:
    date: 14.02.2024
    timezone: GMT+1
    stop:       240  # in minutes
    streaming:
      enable: true
      pause:     60  # in minutes
      prepend:    5  # in minutes
      extend:     5  # in minutes
    demo:
      enable: false
      duration: 300  # in seconds
      pause:     10  # in seconds

  talks:
    # Talk categories
    main_categories:
      - name: WP1
        color: info
      - name: WP2
        color: danger
      - name: WP3
        color: warning
      - name: WP4
        color: purple
      - name: WP5
        color: success
      - name: WP6
        color: dark
      - name: WP7
        color: primary
      - name: WP8
        color: brown
      - name: WP9
        color: pink
          

    # Hide icons on talk overview page
    hide_icons: false

  speakers:
    # Show first and last name
    show_firstname: true

  location:
    # Disable links to locations
    hide: false
    # URL of location / room overview page
    url: '/location'
    # Main page title shown on location/room navigation bar
    navbar_title: 'Location'
    # Show map on location main page.  Set `map: false` if you don't want to
    # display it.
    map:
      # Initial map center point
      home_coord: 40.824786543313365, 14.194593429565431
      # Alternative map providers can be found on https://leaflet-extras.github.io/leaflet-providers/preview/
      # The following do match the Bootstrap design not too badly:
      #   - Thunderforest.Neighbourhood
      #   - Esri.WorldTopoMap
      map_provider: "OpenStreetMap.Mapnik"
      default_zoom: 16


  program:
    # URL of program page
    url: '/program'

    # Time steps in program table
    time_steps: 30 # in minutes

    # Show intermediary time steps (next to full hours)
    show_alltimes: true
